include 'routines/FLTMAX.asm'
include 'routines/print4h.asm'
include 'routines/print8h.asm'
include 'routines/print16h.asm'
include 'routines/print24h.asm'
include 'routines/print32h.asm'
;include 'routines/printf.asm'
;include 'routines/sprintf.asm'
include 'routines/strtok.asm'

include 'routines/clearHeap.asm'
include 'routines/heapAlloc.asm'
include 'routines/pushOP.asm'
include 'routines/popOP.asm'
include 'routines/mov11b.asm'
include 'routines/mov9ToOP.asm'
include 'routines/mov9b.asm'
include 'routines/mov8b.asm'
